### ISSUE TITLE
Pasting into Git Bash - Incorrect Shortcut

### ISSUE THREAD

**Issue by drkfitz13** [learn-co-curriculum/dsc-git-intro#2]
The lesson says to **ctrl + v** the URL into git bash when cloning a lesson, but that doesn't work (on windows). I think what a previous lesson said is that the shortcut is **ctrl + insert**, which seemed to work on my machine.

**Comment by Cheffrey2000** [comment]
This issue has been fixed with the following commit: [0ab70a3](https://github.com/learn-co-curriculum/dsc-git-intro/commit/0ab70a343745a11eeaa34d68fbe48758606d7dba)
